# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lens < Formula
  desc "Domain-agnostic conversational AI evaluation harness"
  homepage "https://github.com/mgm702/lens"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mgm702/lens/releases/download/v0.1.0/lens_darwin_amd64.tar.gz"
      sha256 "222fb2945f79c2835e1e991bcf07352f8eb4e86e960506fc4312d73c1088dc8c"

      define_method(:install) do
        bin.install "lens"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mgm702/lens/releases/download/v0.1.0/lens_darwin_arm64.tar.gz"
      sha256 "2bd1628a69d01a7638b36963c643efabcde99b3d372bb87098304f6e38fcd0d5"

      define_method(:install) do
        bin.install "lens"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mgm702/lens/releases/download/v0.1.0/lens_linux_amd64.tar.gz"
      sha256 "e4f87a7df3666f340cec68c06afe308527df8bc0d3e2e0e5dfc5e1341d8db580"
      define_method(:install) do
        bin.install "lens"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mgm702/lens/releases/download/v0.1.0/lens_linux_arm64.tar.gz"
      sha256 "4cfa63c45f87bf845d5908d38bfa5b6f1b24e345cc7a175536877845e3187b22"
      define_method(:install) do
        bin.install "lens"
      end
    end
  end

  test do
    system "#{bin}/lens", "--version"
  end
end
